# This file has been automatically generated by the DICE Simulation Tool.
# Comment lines starting with # SIM # contain important metadata needed to
# plot this datafile within the Simulation Tool environment, and should
# not be removed.

# SIM # BEGIN-RESERVED-COMMENTS
# SIM # ID: 58176150-b677-489a-9f56-9a87227d57fa
# SIM # X Label: arr
# SIM # X Unit: null
# SIM # Y Label: utilization
# SIM # Y Unit: percentage
# SIM # SLA value: null
# SIM # SLA unit: null
# SIM # END-RESERVED-COMMENTS

# arr	utilization	id
1	4.687	"bb57d16c-94b0-4a4b-8a87-85f2625b2c05"
5	22.178	"9f49f374-f653-4217-aa14-60ba02e89868"
10	42.771	"92d88fc5-6935-4143-99bd-89d5249aa4d3"
18	80.052	"e6c8cb3c-c947-4d5f-96b5-61ee86a38e0d"
28	88.275	"7d5d7235-4f6e-4652-b60e-241f9f7dde2d"
39	84.547	"9f409229-17f7-46ee-bc07-7f3ee39fcea6"
