# This file has been automatically generated by the DICE Simulation Tool.
# Comment lines starting with # SIM # contain important metadata needed to
# plot this datafile within the Simulation Tool environment, and should
# not be removed.

# SIM # BEGIN-RESERVED-COMMENTS
# SIM # ID: 58176150-b677-489a-9f56-9a87227d57fa
# SIM # X Label: arr
# SIM # X Unit: null
# SIM # Y Label: throughput
# SIM # Y Unit: Hz
# SIM # SLA value: null
# SIM # SLA unit: null
# SIM # END-RESERVED-COMMENTS

# arr	throughput	id
1	1.019	"bb57d16c-94b0-4a4b-8a87-85f2625b2c05"
5	4.989	"9f49f374-f653-4217-aa14-60ba02e89868"
10	9.797	"92d88fc5-6935-4143-99bd-89d5249aa4d3"
18	17.92	"e6c8cb3c-c947-4d5f-96b5-61ee86a38e0d"
28	20.852	"7d5d7235-4f6e-4652-b60e-241f9f7dde2d"
39	20.57	"9f409229-17f7-46ee-bc07-7f3ee39fcea6"
