# This file has been automatically generated by the DICE Simulation Tool.
# Comment lines starting with # SIM # contain important metadata needed to
# plot this datafile within the Simulation Tool environment, and should
# not be removed.

# SIM # BEGIN-RESERVED-COMMENTS
# SIM # ID: 87e7e2ca-c145-4097-add5-6f7398177dfe
# SIM # X Label: arrRate
# SIM # X Unit: null
# SIM # Y Label: throughput
# SIM # Y Unit: Hz
# SIM # SLA value: null
# SIM # SLA unit: null
# SIM # END-RESERVED-COMMENTS

# arrRate	throughput	id
1	1.005	"3678f5ed-cbf0-479b-a34e-d5ce3a0017f6"
4	4.003	"5042402d-3bbb-4c74-88ee-50363fdeed86"
10	5.265	"c3967c3e-cd8c-446f-9ccf-15efbb978cbd"
18	5.943	"d990dad7-6d08-4cde-abc4-41a0dfe9a54e"
28	7.061	"2f67e128-c338-47cf-a065-9e8073d36069"
39	7.368	"03303369-ff2b-4424-b614-4fb62a781f80"
