# This file has been automatically generated by the DICE Simulation Tool.
# Comment lines starting with # SIM # contain important metadata needed to
# plot this datafile within the Simulation Tool environment, and should
# not be removed.

# SIM # BEGIN-RESERVED-COMMENTS
# SIM # ID: c09f7aa0-cdb3-412a-b382-4d2d1267d261
# SIM # X Label: lambda
# SIM # X Unit: null
# SIM # Y Label: throughput
# SIM # Y Unit: Hz
# SIM # SLA value: null
# SIM # SLA unit: null
# SIM # END-RESERVED-COMMENTS

# lambda	throughput	id
0.02	0.02	"f80410da-032c-4b89-b740-bf70c7861c1f"
0.2	0.201	"e8b05a94-c74d-4071-bc88-82fec91d6746"
1	1.012	"7d8291f8-c206-4af7-8e1f-51fa9eb68130"
10	10.032	"a4469a90-c9c2-4ae7-8154-313866451c1c"
100	99.894	"796fa4ce-157f-4331-9e86-646489deda28"
1,000	959.753	"7140ba0e-e90c-4458-8515-049b1eef4cc5"
